### ISSUE TITLE
 Write User Input to a File

### ISSUE THREAD

**Issue by infoyouth** [shweta-borganve/python-course#2]
Create a Python script that prompts the user for input and writes the input to a file.

Example Input:
```
User input: This is a test.
```
Expected Output:

A file named ```output.txt``` with the following contents:
```
This is a test.
```

**Comment by shweta-borganve** [comment]
with open("output.txt","w") as f:
    f.write("This is a test.")

**Comment by shweta-borganve** [comment]
This is a test.

**Comment by shweta-borganve** [comment]
![Screenshot 2024-06-09 004227](https://github.com/shweta-borganve/python-course/assets/148645234/ddf23091-a39f-4139-968f-b3ee7a15ef1e)

**Comment by shweta-borganve** [comment]
![Screenshot 2024-06-09 004413](https://github.com/shweta-borganve/python-course/assets/148645234/c7334292-4723-44d8-9ed8-1e31de8ee96f)
