### ISSUE TITLE
Reading and Writing Text Files

### ISSUE THREAD

**Issue by shweta-borganve** [shweta-borganve/python-course#3]
![Screenshot 2024-06-10 223359](https://github.com/shweta-borganve/python-course/assets/148645234/d32975f0-6e76-40c5-a372-910107a6a302)

**Comment by shweta-borganve** [comment]
![Screenshot 2024-06-10 223527](https://github.com/shweta-borganve/python-course/assets/148645234/c5f43458-6b06-4079-923a-38268bae430b)

**Comment by shweta-borganve** [comment]
![Screenshot 2024-06-10 223621](https://github.com/shweta-borganve/python-course/assets/148645234/c5d749d8-509b-4e06-80db-a535f5372963)

**Comment by DarshanBoraganve** [comment]
[
![image](https://github.com/shweta-borganve/python-course/assets/161494232/0edb3343-707a-4d50-96cf-1f5fd4eabb34)
](url)

**Comment by DarshanBoraganve** [comment]
![Uploading image.jpg…]()

**Comment by DarshanBoraganve** [comment]
![Uploading image.jpg…]()
